
server:
  port: 8081
  
spring:  datasource:    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    
      jpa:    hibernate:      ddl-auto: update  
    show-sql: true
    
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MYSQLDialect  application:    name: user-service 
    
  config:    import: optional:configserver:http://localhost:8084
        
#eureka:#  instance:#    prefer-ip-address: true
#    
#  client:#    fetch-registry: true
#    register-with-eureka: true
#    service-url:#      defaultZone: http://localhost:8761/eureka
#         
  
    
          
    